#!/bin/bash
#PBS -N NYS_PySAM_Optimization
#PBS -q medium
#PBS -J 1-100
#PBS -l select=1:ncpus=112:mpiprocs=112
#PBS -l place=pack
#PBS -j oe
#PBS -M 23b0343@iitb.ac.in
#PBS -m abe

cd $PBS_O_WORKDIR

# --- Secure Authentication ---
# Read the token from the restricted file into a variable
if [ -f "$HOME/.dagshub_token" ]; then
    export MLFLOW_TRACKING_PASSWORD=$(cat "$HOME/.dagshub_token")
    export MLFLOW_TRACKING_USERNAME="aryanvj787"
    export MLFLOW_TRACKING_URI="https://dagshub.com/aryanvj787/NYS-Design-Optimisation-using-PySAM.mlflow"
else
    echo "Warning: .dagshub_token file not found. MLflow might fail."
fi

# Load spack, activate venv...
spack load /icxqzpn
source .venv/bin/activate

# Use the environment variable PBS provides to be safe
export APP_CPU_COUNT=$PBS_NCPUS

# avoid inherent parallelism
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

# Execution 
echo "Starting optimization on $(hostname) using $APP_CPU_COUNT CPUs..."
uv run python3 main.py